### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ToddGreenfield** [skarcha/node-nut#2]
Please see https://github.com/ToddGreenfield/homebridge-nut/issues/7 which is a plugin using this module. Do you have any ideas what is causing the below error with node-nut?

/usr/local/lib/node_modules/homebridge-nut/node_modules/node-nut/node-nut.js:71
vars[matches[1]] = matches[2];
^

TypeError: Cannot read property '1' of null
at parseKeyValueList (/usr/local/lib/node_modules/homebridge-nut/node_modules/node-nut/node-nut.js:71:16)
at Nut.parseFunc (/usr/local/lib/node_modules/homebridge-nut/node_modules/node-nut/node-nut.js:87:3)
at Socket. (/usr/local/lib/node_modules/homebridge-nut/node_modules/node-nut/node-nut.js:33:9)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at Socket.Readable.push (_stream_readable.js:134:10)
at TCP.onread (net.js:543:20)

**Comment by yeya** [comment]
The error occurs when a line contains a var without value, for example: `VAR UPS ups.model ""`
I think the bug is in this regex: [https://github.com/skarcha/node-nut/blob/master/node-nut.js#L71](url)
It doesn't handle empty value correctly.
