### ISSUE TITLE
How to use username and password?

### ISSUE THREAD

**Issue by christian-ek** [skarcha/node-nut#8]
Hello!
I am new to using node js and I'm trying to use node-nut with username and password but I'm getting an error.
I installed version 1.0.3 from npm

This is my code:
```
var Nut = require('node-nut');

oNut = new Nut(3493, '10.0.0.60');

oNut.on('error', function(err) {
	console.log('There was an error: ' + err);
});

oNut.on('close', function() {
	console.log('Connection closed.');
});

oNut.on('ready', function() {
	self = this;
	this.GetUPSList(function(upslist, err) {
        if (err) console.log('Error: ' + err)
        console.log(upslist);
		self.close();
	});
});

oNut.SetUsername('monuser');

oNut.SetPassword('secret');

oNut.start();
```

Error:
```
⋊> ~ node app.js
There was an error when setting username: Other communication still running

There was an error when setting username: null
/Users/ce/node_modules/node-nut/node-nut.js:56
		this._client.write(cmd + '\n');
		             ^

TypeError: Cannot read property 'write' of undefined
    at Nut.send (/Users/ce/node_modules/node-nut/node-nut.js:56:16)
    at Nut.SetPassword (/Users/ce/node_modules/node-nut/node-nut.js:307:7)
    at Object.<anonymous> (/Users/ce/app.js:26:6)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jimklimov** [comment]
Cursorily, seems like the logic is asynchronous here, so you'd need to delay password-setting after username-setting (wait for `ready` like elsewhere).

From code it looks like "setting" these actually calls the NUT protocol to validate immediately (no separate "login" action with prepared values in sight).

**Comment by jonferreira** [comment]
> Cursorily, seems like the logic is asynchronous here, so you'd need to delay password-setting after username-setting (wait for `ready` like elsewhere).
> 
> From code it looks like "setting" these actually calls the NUT protocol to validate immediately (no separate "login" action with prepared values in sight).

Can you let me know *how* to do what you say?

I'm trying to add some extra capabilities to node-red-contrib-nut and for that I need to login.

By default it has `nut.SetUsername(upsUser, () => nut.SetPassword(upsPass, () => nut.start()))` but I'm getting the above error with the ocasional `Other communication still running`

It feels like I should `await `these calls but those aren't `async `methods so I can't

**Comment by jimklimov** [comment]
Alas no, not to that depth of detail - never coded in Node.
